version: '2'
services:

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
     - "9091:9091"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - ./prometheus_jenkins.yml:/etc/prometheus/prometheus.yml
    ports:
     - "9090:9090"
    links:
     - pushgateway
     - cadvisor

  cadvisor:
   image: google/cadvisor
   container_name: cadvisor
   volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
   ports:
    - "8090:8080"

  son-emu:
    image: registry.sonata-nfv.eu:5000/son-emu
    container_name: son-emu
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"
    pid: "host"
    privileged: true
    ports:
     #REST api
     - "5001:5001"
    entrypoint: 
     - "/son-emu/utils/ci/entrypoint_docker-compose.sh"
    command: [python, src/emuvim/examples/son-monitor_default_topo.py]


